### ISSUE TITLE
测试请求

### ISSUE THREAD

**Issue by Wsine** [Wsine/Peekerpoke#1]
1. 现在原有代码已经重构完毕，希望你能够测试一下@liby3
2. API文档我没还没写，等我找到好的方法再写，现在如果遇到什么问题请你尽量解决一下
3. 可能遇到的问题：变量名不存在；缺少include文件；类的方法调用权限；等；（因为是在纯文本编辑器下写的代码，请体谅）
4. makefile文件理论上还能用，不能用的话，建议尝试修改一下
5. **请不要随意强制覆盖master分支，避免回滚不了的情况**

**Comment by Wsine** [comment]
1. Poke模块的代码已经重构完毕且成功编译
2. 希望你能尽量模仿Poke的写法，完成Peek的重构 @liby3 
3. Poke的代码已经全部推送到master分支上，请自行pull master分支，可能会遇到conflict，**一定要解决conflict**，不懂可以问
4. 待会我会写一份《开发文档规范》在该工程的wiki上，有空请看看
5. 没事不用回复邮件，我知道你一定会收到邮件的。
6. 如果觉得某些issue的主题你不想关注，可以点击右侧的Unsubscribe，例如开发笔记

**Comment by Wsine** [comment]
@liby3 
API文档已经搭建框架完毕，希望你能完成Poke和Peek两个模块的API文档编写。开始编写前，希望能先阅读一下[开发文档规范](https://github.com/Wsine/Peekerpoke/wiki/%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83)，效果样式在/doc/html/index.html文件中，可以去查看一下。
这步工作不急，可以先完成论文和推进项目功能，利用晚上或一些零碎时间撰写API文档即可。
如果你想自己生成API文档，Win平台[下载doxygen](http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.11.windows.x64.bin.zip){绿色软件}，使用`make doc`编译生成；或者，只是修改源文件添加注释即可。

Again：诸如辛苦了收到了等回复可不必，因为会收到邮件提醒的=。=

**Comment by liby3** [comment]
通信部分出现了一个严肃的问题，我调了两天也不行，今天下午还得去调试。

发自我的 iPhone
